name: PPP Scraper Scheduler

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Scrape Evetech
        run: |
          curl https://ppp-scraper.herokuapp.com/scrape?file=evetech,
          curl https://ppp-scraper.herokuapp.com/scrape?file=dreamware,
          curl https://ppp-scraper.herokuapp.com/scrape?file=titan-ice
